version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:10-stretch
    working_directory: ~/trudesk

commands:
  yarninstall:
    steps:
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Install Dependencies
        command: yarn install --frozen-lockfile
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn

jobs:
  build_production:
    docker:
    - image: circleci/node:10-stretch
    - image: circleci/mongo:3.6
    working_directory: ~/trudesk
    steps:
    - checkout
    - yarninstall
    - run:
        name: Run Tests
        command: yarn run test
    - run:
        name: Add to know hosts
        command: ssh-keyscan $DODOMAIN >> ~/.ssh/known_hosts
    - run:
        name: Deploy Digital Ocean
        command: ssh $DOUSER@$DODOMAIN "cd /root/trudesk; git pull; npm install; pm2 restart trudesk;"

workflows:
  version: 2.1
  production:
    jobs:
    - build_production:
        filters:
          branches:
            only: master