version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:10-stretch
    working_directory: ~/trudesk

commands:
  npminstall:
    steps:
    - restore_cache:
        name: Restore NPM Package Cache
        keys:
        - npm-packages-{{ checksum "package-lock.json" }}
    - run:
        name: Install Dependencies
        command: npm install
    - save_cache:
        name: Save NPM Package Cache
        key: npm-packages-{{ checksum "package-lock.json" }}
        paths:
        - ~/.cache/npm

jobs:
  build_production:
    docker:
    - image: circleci/node:10-stretch
    - image: circleci/mongo:3.6
    working_directory: ~/trudesk
    steps:
    - checkout
    - npminstall
    - run:
        name: Run Tests
        command: npm run test
    - run:
        name: Add to know hosts
        command: ssh-keyscan $DODOMAIN >> ~/.ssh/known_hosts
    - run:
        name: Deploy Digital Ocean
        command: ssh $DOUSER@$DODOMAIN "cd /var/www/trudesk; git pull; npm install; pm2 restart trudesk;"

workflows:
  version: 2.1
  production:
    jobs:
    - build_production:
        filters:
          branches:
            only: master